

test_that("select test", {
  skip_on_cran()

  fixture1 <-
    structure(
      list(
        new_name = structure(1L, .Label = "ce3agefc", class = "factor"),
        varlab = structure(1L, .Label = "age of focus child", class = "factor"),
        old_name = structure(1L, .Label = "ffcc_centobs_agefc", class = "factor"),
        type = structure(1L, .Label = "cont", class = "factor"),
        warning = structure(1L, .Label = "0", class = "factor"),
        group = structure(1L, .Label = "530", class = "factor"),
        q_group_N = structure(1L, .Label = "2", class = "factor"),
        topic1 = structure(1L, .Label = "* topic1 coming soon! *",
                           class = "factor"),
        topic2 = structure(1L, .Label = "", class = "factor"),
        source = structure(1L, .Label = "constructed", class = "factor"),
        respondent = structure(1L, .Label = "e", class = "factor"),
        wave = structure(1L, .Label = "3", class = "factor"),
        scope = structure(1L, .Label = "20", class = "factor"),
        section = structure(1L, .Label = "", class = "factor"),
        leaf = structure(1L, .Label = "agefc", class = "factor"),
        q_group_list = structure(1L, .Label = "ce3agefc cs3age",
                                 class = "factor"),
        value1 = structure(1L, .Label = "-9", class = "factor"),
        label1 = structure(1L, .Label = "-9 Not in wave", class = "factor"),
        value2 = structure(1L, .Label = "-8", class = "factor"),
        label2 = structure(1L, .Label = "-8 Out of range", class = "factor"),
        value3 = structure(1L, .Label = "-7", class = "factor"),
        label3 = structure(1L, .Label = "-7 N/A", class = "factor"),
        value4 = structure(1L, .Label = "-6", class = "factor"),
        label4 = structure(1L, .Label = "-6 Skip", class = "factor"),
        value5 = structure(1L, .Label = "-5", class = "factor"),
        label5 = structure(1L, .Label = "-5 Not asked", class = "factor"),
        value6 = structure(1L, .Label = "-4", class = "factor"),
        label6 = structure(1L, .Label = "-4 Multiple ans", class = "factor"),
        value7 = structure(1L, .Label = "-3", class = "factor"),
        label7 = structure(1L, .Label = "-3 Missing", class = "factor"),
        value8 = structure(1L, .Label = "-2", class = "factor"),
        label8 = structure(1L, .Label = "-2 Don't know", class = "factor"),
        value9 = structure(1L, .Label = "-1", class = "factor"),
        label9 = structure(1L, .Label = "-1 Refuse", class = "factor"),
        value10 = structure(1L, .Label = "", class = "factor"),
        label10 = structure(1L, .Label = "", class = "factor"),
        value11 = structure(1L, .Label = "", class = "factor"),
        label11 = structure(1L, .Label = "", class = "factor"),
        value12 = structure(1L, .Label = "", class = "factor"),
        label12 = structure(1L, .Label = "", class = "factor"),
        value13 = structure(1L, .Label = "", class = "factor"),
        label13 = structure(1L, .Label = "", class = "factor"),
        value14 = structure(1L, .Label = "", class = "factor"),
        label14 = structure(1L, .Label = "", class = "factor"),
        value15 = structure(1L, .Label = "", class = "factor"),
        label15 = structure(1L, .Label = "", class = "factor"),
        value16 = structure(1L, .Label = "", class = "factor"),
        label16 = structure(1L, .Label = "", class = "factor"),
        value17 = structure(1L, .Label = "", class = "factor"),
        label17 = structure(1L, .Label = "", class = "factor"),
        value18 = structure(1L, .Label = "", class = "factor"),
        label18 = structure(1L, .Label = "", class = "factor"),
        value19 = structure(1L, .Label = "", class = "factor"),
        label19 = structure(1L, .Label = "", class = "factor"),
        value20 = structure(1L, .Label = "", class = "factor"),
        label20 = structure(1L, .Label = "", class = "factor"),
        value21 = structure(1L, .Label = "", class = "factor"),
        label21 = structure(1L, .Label = "", class = "factor"),
        value22 = structure(1L, .Label = "", class = "factor"),
        label22 = structure(1L, .Label = "", class = "factor"),
        value23 = structure(1L, .Label = "", class = "factor"),
        label23 = structure(1L, .Label = "", class = "factor"),
        value24 = structure(1L, .Label = "", class = "factor"),
        label24 = structure(1L, .Label = "", class = "factor"),
        value25 = structure(1L, .Label = "", class = "factor"),
        label25 = structure(1L, .Label = "", class = "factor"),
        value26 = structure(1L, .Label = "", class = "factor"),
        label26 = structure(1L, .Label = "", class = "factor"),
        value27 = structure(1L, .Label = "", class = "factor"),
        label27 = structure(1L, .Label = "", class = "factor"),
        value28 = structure(1L, .Label = "", class = "factor"),
        label28 = structure(1L, .Label = "", class = "factor"),
        value29 = structure(1L, .Label = "", class = "factor"),
        label29 = structure(1L, .Label = "", class = "factor"),
        value30 = structure(1L, .Label = "", class = "factor"),
        label30 = structure(1L, .Label = "", class = "factor"),
        value31 = structure(1L, .Label = "", class = "factor"),
        label31 = structure(1L, .Label = "", class = "factor"),
        value32 = structure(1L, .Label = "", class = "factor"),
        label32 = structure(1L, .Label = "", class = "factor"),
        value33 = structure(1L, .Label = "", class = "factor"),
        label33 = structure(1L, .Label = "", class = "factor"),
        value34 = structure(1L, .Label = "", class = "factor"),
        label34 = structure(1L, .Label = "", class = "factor"),
        value35 = structure(1L, .Label = "", class = "factor"),
        label35 = structure(1L, .Label = "", class = "factor"),
        value36 = structure(1L, .Label = "", class = "factor"),
        label36 = structure(1L, .Label = "", class = "factor"),
        value37 = structure(1L, .Label = "", class = "factor"),
        label37 = structure(1L, .Label = "", class = "factor"),
        value38 = structure(1L, .Label = "", class = "factor"),
        label38 = structure(1L, .Label = "", class = "factor"),
        value39 = structure(1L, .Label = "", class = "factor"),
        label39 = structure(1L, .Label = "", class = "factor"),
        value40 = structure(1L, .Label = "", class = "factor"),
        label40 = structure(1L, .Label = "", class = "factor"),
        value41 = structure(1L, .Label = "", class = "factor"),
        label41 = structure(1L, .Label = "", class = "factor"),
        value42 = structure(1L, .Label = "", class = "factor"),
        label42 = structure(1L, .Label = "", class = "factor"),
        value43 = structure(1L, .Label = "", class = "factor"),
        label43 = structure(1L, .Label = "", class = "factor"),
        value44 = structure(1L, .Label = "", class = "factor"),
        label44 = structure(1L, .Label = "", class = "factor"),
        value45 = structure(1L, .Label = "", class = "factor"),
        label45 = structure(1L, .Label = "", class = "factor"),
        value46 = structure(1L, .Label = "", class = "factor"),
        label46 = structure(1L, .Label = "", class = "factor"),
        value47 = structure(1L, .Label = "", class = "factor"),
        label47 = structure(1L, .Label = "", class = "factor"),
        value48 = structure(1L, .Label = "", class = "factor"),
        label48 = structure(1L, .Label = "", class = "factor"),
        value49 = structure(1L, .Label = "", class = "factor"),
        label49 = structure(1L, .Label = "", class = "factor"),
        value50 = structure(1L, .Label = "", class = "factor"),
        label50 = structure(1L, .Label = "", class = "factor"),
        value51 = structure(1L, .Label = "", class = "factor"),
        label51 = structure(1L, .Label = "", class = "factor"),
        value52 = structure(1L, .Label = "", class = "factor"),
        label52 = structure(1L, .Label = "", class = "factor"),
        value53 = structure(1L, .Label = "", class = "factor"),
        label53 = structure(1L, .Label = "", class = "factor"),
        value54 = structure(1L, .Label = "", class = "factor"),
        label54 = structure(1L, .Label = "", class = "factor"),
        value55 = structure(1L, .Label = "", class = "factor"),
        label55 = structure(1L, .Label = "", class = "factor"),
        value56 = structure(1L, .Label = "", class = "factor"),
        label56 = structure(1L, .Label = "", class = "factor"),
        value57 = structure(1L, .Label = "", class = "factor"),
        label57 = structure(1L, .Label = "", class = "factor"),
        value58 = structure(1L, .Label = "", class = "factor"),
        label58 = structure(1L, .Label = "", class = "factor"),
        value59 = structure(1L, .Label = "", class = "factor"),
        label59 = structure(1L, .Label = "", class = "factor"),
        value60 = structure(1L, .Label = "", class = "factor"),
        label60 = structure(1L, .Label = "", class = "factor"),
        value61 = structure(1L, .Label = "", class = "factor"),
        label61 = structure(1L, .Label = "", class = "factor"),
        value62 = structure(1L, .Label = "", class = "factor"),
        label62 = structure(1L, .Label = "", class = "factor"),
        value63 = structure(1L, .Label = "", class = "factor"),
        label63 = structure(1L, .Label = "", class = "factor"),
        value64 = structure(1L, .Label = "", class = "factor"),
        label64 = structure(1L, .Label = "", class = "factor"),
        value65 = structure(1L, .Label = "", class = "factor"),
        label65 = structure(1L, .Label = "", class = "factor"),
        value66 = structure(1L, .Label = "", class = "factor"),
        label66 = structure(1L, .Label = "", class = "factor"),
        value67 = structure(1L, .Label = "", class = "factor"),
        label67 = structure(1L, .Label = "", class = "factor"),
        value68 = structure(1L, .Label = "", class = "factor"),
        label68 = structure(1L, .Label = "", class = "factor")
      ),
      .Names = c(
        "new_name",
        "varlab",
        "old_name",
        "type",
        "warning",
        "group",
        "q_group_N",
        "topic1",
        "topic2",
        "source",
        "respondent",
        "wave",
        "scope",
        "section",
        "leaf",
        "q_group_list",
        "value1",
        "label1",
        "value2",
        "label2",
        "value3",
        "label3",
        "value4",
        "label4",
        "value5",
        "label5",
        "value6",
        "label6",
        "value7",
        "label7",
        "value8",
        "label8",
        "value9",
        "label9",
        "value10",
        "label10",
        "value11",
        "label11",
        "value12",
        "label12",
        "value13",
        "label13",
        "value14",
        "label14",
        "value15",
        "label15",
        "value16",
        "label16",
        "value17",
        "label17",
        "value18",
        "label18",
        "value19",
        "label19",
        "value20",
        "label20",
        "value21",
        "label21",
        "value22",
        "label22",
        "value23",
        "label23",
        "value24",
        "label24",
        "value25",
        "label25",
        "value26",
        "label26",
        "value27",
        "label27",
        "value28",
        "label28",
        "value29",
        "label29",
        "value30",
        "label30",
        "value31",
        "label31",
        "value32",
        "label32",
        "value33",
        "label33",
        "value34",
        "label34",
        "value35",
        "label35",
        "value36",
        "label36",
        "value37",
        "label37",
        "value38",
        "label38",
        "value39",
        "label39",
        "value40",
        "label40",
        "value41",
        "label41",
        "value42",
        "label42",
        "value43",
        "label43",
        "value44",
        "label44",
        "value45",
        "label45",
        "value46",
        "label46",
        "value47",
        "label47",
        "value48",
        "label48",
        "value49",
        "label49",
        "value50",
        "label50",
        "value51",
        "label51",
        "value52",
        "label52",
        "value53",
        "label53",
        "value54",
        "label54",
        "value55",
        "label55",
        "value56",
        "label56",
        "value57",
        "label57",
        "value58",
        "label58",
        "value59",
        "label59",
        "value60",
        "label60",
        "value61",
        "label61",
        "value62",
        "label62",
        "value63",
        "label63",
        "value64",
        "label64",
        "value65",
        "label65",
        "value66",
        "label66",
        "value67",
        "label67",
        "value68",
        "label68"
      ),
      row.names = 1L,
      class = "data.frame"
    )


  select1 <- select_metadata(variable_name = "ce3agefc")
  expect_identical(fixture1, select1)

  fixture2 <- structure("cont", .Names = "type")
  select2 <-
    select_metadata(variable_name = "ce3agefc", field_name = "type")
  expect_identical(fixture2, select2)

})

test_that("search test", {
  skip_on_cran()

  fixture1 <-
    structure(
      list(
        new_name = structure(
          1:2,
          .Label = c(
            "cf1finjail",
            "cf2fevjail",
            "cf2finjail",
            "cf3fevjail",
            "cf3finjail",
            "cf4fevjail",
            "cf4finjail",
            "cf5fevjail",
            "cf5finjail",
            "cm1ffinjail",
            "cm1finjail",
            "cm2fevjail",
            "cm2ffevjail",
            "cm2ffinjail",
            "cm2finjail",
            "cm3fevjail",
            "cm3ffevjail",
            "cm3ffinjail",
            "cm3finjail",
            "cm4fevjail",
            "cm4ffevjail",
            "cm4ffinjail",
            "cm4finjail",
            "cm5fevjail",
            "cm5ffevjail",
            "cm5ffinjail",
            "cm5finjail",
            "f2a8c",
            "f2a8d",
            "f2h18",
            "f2h19",
            "f2h20",
            "f2h20a",
            "f2h20b1",
            "f2h20b10",
            "f2h20b11",
            "f2h20b12",
            "f2h20b13",
            "f2h20b14",
            "f2h20b15",
            "f2h20b16",
            "f2h20b17",
            "f2h20b18",
            "f2h20b19",
            "f2h20b2",
            "f2h20b3",
            "f2h20b4",
            "f2h20b5",
            "f2h20b6",
            "f2h20b7",
            "f2h20b8",
            "f2h20b9",
            "f2h21",
            "f2h21a",
            "f2h21b",
            "f2h21c2",
            "f2h21d1",
            "f2h21d10",
            "f2h21d11",
            "f2h21d12",
            "f2h21d13",
            "f2h21d14",
            "f2h21d15",
            "f2h21d16",
            "f2h21d17",
            "f2h21d18",
            "f2h21d19",
            "f2h21d2",
            "f2h21d3",
            "f2h21d4",
            "f2h21d5",
            "f2h21d6",
            "f2h21d7",
            "f2h21d8",
            "f2h21d9",
            "f2h22",
            "f2h22a",
            "f2h23",
            "f2h23a",
            "f2h24",
            "f2h24a",
            "f2h25",
            "f2h25a2",
            "f2h26b",
            "f2h27",
            "f3a8b_3",
            "f3a8b_4",
            "f3c21d_7",
            "f3c38c_7",
            "f3c42",
            "f3c42a_4",
            "f3c42a_5",
            "f3c42a_6",
            "f3c42b",
            "f3c42c1",
            "f3c42c2",
            "f3c42c3",
            "f3c42c4",
            "f3c42d2",
            "f3c42e2",
            "f3i26",
            "f3i26b_2",
            "f3i26b_3",
            "f3i26b_4",
            "f3i26b_5",
            "f3i26b_6",
            "f3i26b_7",
            "f3i27a",
            "f3i27d2",
            "f3i28_2",
            "f3i28_3",
            "f3i28_4",
            "f3i28_5",
            "f3i28_6",
            "f3i28_7",
            "f3i29",
            "f3i30",
            "f3i30a",
            "f3i31",
            "f3i31a",
            "f3i31c2",
            "f3i32",
            "f4a8b_3",
            "f4a8b_4",
            "f4c21d_7",
            "f4c37a_1",
            "f4c37a_4",
            "f4c37a_6",
            "f4c37a_7",
            "f4c37a_8",
            "f4c37b",
            "f4c37c1",
            "f4c37c2",
            "f4c37c3",
            "f4c37c4",
            "f4c37d2",
            "f4c37e2",
            "f4i26",
            "f4i26b_4",
            "f4i26b_5",
            "f4i26b_6",
            "f4i26b_7",
            "f4i28_4",
            "f4i28_5",
            "f4i28_6",
            "f4i28_7",
            "f4i29",
            "f5b26x_1",
            "f5b26x_10",
            "f5b26x_2",
            "f5b26x_3",
            "f5b26x_4",
            "f5b26x_5",
            "f5b26x_6",
            "f5b26x_7",
            "f5b26x_9",
            "f5d23",
            "f5f26",
            "f5f26b2_1",
            "f5f26b2_10",
            "f5f26b2_2",
            "f5f26b2_3",
            "f5f26b2_4",
            "f5f26b2_5",
            "f5f26b2_6",
            "f5f26b2_7",
            "f5f26b2_9",
            "f5f28a_1",
            "f5f28a_10",
            "f5f28a_2",
            "f5f28a_3",
            "f5f28a_4",
            "f5f28a_5",
            "f5f28a_6",
            "f5f28a_7",
            "f5f28a_9",
            "f5f28b",
            "f5f28c",
            "f5f28e",
            "f5f29",
            "m2a9c",
            "m2a9d",
            "m2c33d2",
            "m2c33e2",
            "m2c36",
            "m2c36a1",
            "m2c36a14",
            "m2c36a17",
            "m2c36a18",
            "m2c36a19",
            "m2c36a2",
            "m2c36a3",
            "m2c36a7",
            "m2c36a8",
            "m2c37a1",
            "m2c37a2",
            "m2c37a3",
            "m2c37a4",
            "m2e10",
            "m3a8b_3",
            "m3a8b_4",
            "m3c42",
            "m3c42a_1",
            "m3c42a_4",
            "m3c42a_5",
            "m3c42a_6",
            "m3c42a_8",
            "m3c42b",
            "m3c42c1",
            "m3c42c2",
            "m3c42c3",
            "m3c42c4",
            "m3c42d2",
            "m3c42e2",
            "m3i26",
            "m3i26b_2",
            "m3i26b_3",
            "m3i26b_4",
            "m3i26b_5",
            "m3i26b_6",
            "m3i26b_7",
            "m3i27a",
            "m3i27d2",
            "m3i28_2",
            "m3i28_3",
            "m3i28_4",
            "m3i28_5",
            "m3i28_6",
            "m3i28_7",
            "m3i29",
            "m3i30",
            "m3i30a",
            "m3i31",
            "m3i31a",
            "m3i31c2",
            "m3i32",
            "m4a8b_3",
            "m4a8b_4",
            "m4c21d_7",
            "m4c37a_4",
            "m4c37a_5",
            "m4c37a_6",
            "m4c37a_7",
            "m4c37a_8",
            "m4c37b",
            "m4c37c1",
            "m4c37c2",
            "m4c37c3",
            "m4c37c4",
            "m4c37d2",
            "m4c37e2",
            "m4e25",
            "m4i26",
            "m4i26b_4",
            "m4i26b_5",
            "m4i26b_6",
            "m4i28_4",
            "m4i28_5",
            "m4i28_6",
            "m4i28_7",
            "m4i28_8",
            "m4i29",
            "m5b30a1_1",
            "m5b30a1_10",
            "m5b30a1_2",
            "m5b30a1_3",
            "m5b30a1_5",
            "m5b30a1_6",
            "m5b30a1_7",
            "m5b30a1_9",
            "m5d23",
            "m5f26",
            "m5f26b2_1",
            "m5f26b2_10",
            "m5f26b2_2",
            "m5f26b2_3",
            "m5f26b2_4",
            "m5f26b2_5",
            "m5f26b2_6",
            "m5f26b2_7",
            "m5f26b2_9",
            "m5f28a_1",
            "m5f28a_10",
            "m5f28a_2",
            "m5f28a_3",
            "m5f28a_4",
            "m5f28a_5",
            "m5f28a_6",
            "m5f28a_7",
            "m5f28a_9",
            "m5f28b",
            "m5f28c",
            "m5f28e",
            "m5f29",
            "p6g23"
          ),
          class = "factor"
        ),
        varlab = structure(
          1:2,
          .Label = c(
            "Constructed - father report, father in jail at his baseline interview",
            "Constructed - father reports, dad ever in jail by his 1yr interview",
            "Constructed - father report, father in jail at his 1 yr interview",
            "Constructed - father report, father ever in jail by his 3yr interview",
            "Constructed - father report, father in jail at his 3yr interview",
            "Constructed - father report, father has spent time in jail by his five-year inte",
            "Constructed - father report, father in jail at his five-year interview",
            "Constructed - father report, father has spent time in jail by his nine-year inte",
            "Constructed - father report, father in jail at his nine-year interview",
            "Constructed - mother and father reports, father in jail at either baseline inter",
            "Constructed - mother report, father in jail at her baseline interview",
            "Constructed - mother reports, dad ever in jail by her 1yr interview",
            "Constructed - mother and father reports, dad ever in jail by either 1yr intervie",
            "Constructed - mother and father reports, father in jail at either 1 yr interview",
            "Constructed - mother report, father in jail at her 1 yr interview",
            "Constructed - mother report, father has spent time in jail by her 3yr interview",
            "Constructed - mother and father reports, dad ever in jail by either 3yr intervie",
            "Constructed - mother and father reports, father in jail at either 3yr interview",
            "Constructed - mother report, father in jail at her 3yr interview",
            "Constructed - mother report, father has spent time in jail by mother five-year i",
            "Constructed - mother and father reports, dad ever in jail by either five-year in",
            "Constructed - mother and father reports, father in jail at either five-year inte",
            "Constructed - mother report, father in jail at mother five-year interview",
            "Constructed - mother report, father has spent time in jail by mother nine-year i",
            "Constructed - mother and father reports, dad ever in jail by either nine-year in",
            "Constructed - mother and father reports, father in jail at either nine-year inte",
            "Why did relationship end? Mother's incarceration",
            "Why did relationship end? Father's incarceration",
            "Have you been stopped by police but not arrested (not for traffic)?",
            "Have you ever been booked or charged w/breaking law?",
            "Do you have any charges pending against you?",
            "How many charges do you have pending against you?",
            "What charges do you have pending ?-Assault",
            "What charges do you have pending ?-Possession/use of marijuana/hashish",
            "What charges do you have pending ?-Sale of marijuana or hashish",
            "What charges do you have pending ?-Possession of other illicit drugs",
            "What charges do you have pending ?-Sale/manufacture of other illicit drugs",
            "What charges do you have pending ?-Major Traffic offense",
            "What charges do you have pending ?-Underage drinking/purchase of alcohol",
            "What charges do you have pending ?-Status offense",
            "What charges do you have pending ?-Non payment of child support",
            "What charges do you have pending ?-Parole or probation violation",
            "What charges do you have pending ?-Other",
            "What charges do you have pending ?-Robbery",
            "What charges do you have pending ?-Theft",
            "What charges do you have pending ?-Theft by deception",
            "What charges do you have pending ?-Crime related to stolen property",
            "What charges do you have pending ?-Destruction of property",
            "What charges do you have pending ?-Other property offense",
            "What charges do you have pending ?-Gambling",
            "What charges do you have pending ?-Commercial vice",
            "Have you ever been convicted of any charges(Not minor traffic)?",
            "How many times have you been convicted of something?",
            "How old were you the first time you were convicted?",
            "When was your most recent conviction?-(Year)",
            "What charges were you convicted of ?-Assault",
            "What charges were you convicted of ?-Possession/use of marijuana/hashish",
            "What charges were you convicted of ?-Sale of marijuana/hashish",
            "What charges were you convicted of ?-Possession of other illicit drugs",
            "What charges were you convicted of ?-Sale/maufacture of other illicit drugs",
            "What charges were you convicted of ?-Major traffic offense",
            "What charges were you convicted of ?-Underage drinking/purchase of alcohol",
            "What charges were you convicted of ?-Status offense",
            "What charges were you convicted of ?-Non payment of child support",
            "What charges were you convicted of ?-Parole or probation violation",
            "What charges were you convicted of ?-Other",
            "What charges were you convicted of ?-Robbery",
            "What charges were you convicted of ?-Theft",
            "What charges were you convicted of ?-Theft by deception",
            "What charges were you convicted of ?-Crime related to stolen property",
            "What charges were you convicted of ?-Destruction of property",
            "What charges were you convicted of ?-Other property offense",
            "What charges were you convicted of ?-Gambling",
            "What charges were you convicted of ?-Commercial vice",
            "Have you ever spent time in correctional institution?",
            "How many times were you sent to a correctional institution?",
            "Was any of this time spent in youth/reform school correctional facilities?",
            "Altogether, how much time did you serve in youth correctional facilities? (month",
            "Did you spend any time in adult correctional facilities?",
            "Altogether, how much time did you serve in adult correctional facilities? (month",
            "How old were you the first time you were incarcerated?",
            "When were you most recently incarcerated?-(Year)",
            "When were you most recently released from incarceration?-(Year)",
            "Were you required to perform community service/be on probation?",
            "Why relationship ended: mother incarceration",
            "Why relationship ended: father incarceration",
            "What action taken: sent to prison?",
            "Has mother ever spent any time in jail?",
            "Why is/was mother in jail: major traffic offense?",
            "Why is/was mother in jail: non-payment of child support?",
            "Why is/was mother in jail: parole or probation violation?",
            "INT CHK: Is mother currently in jail?",
            "Approximately how long did she spend in jail? (years)",
            "Approximately how long did she spend in jail? (months)",
            "Approximately how long did she spend in jail? (weeks)",
            "Approximately how long did she spend in jail? (days)",
            "When did mother go to jail/prison? (year)",
            "When will mother be released from jail/prison? (year)",
            "Charges pending: robbery or theft?",
            "Charges pending: possession/use/sale of drugs?",
            "Charges pending: major traffic offense?",
            "Charges pending: non-payment of child support?",
            "Charges pending: parole or probation violation?",
            "Charges pending: simple assault?",
            "When was your most recent conviction? (year)",
            "Charges convicted: robbery or theft?",
            "Charges convicted: possession/use/sale of drugs?",
            "Charges convicted: major traffic offense?",
            "Charges convicted: non-payment of child support?",
            "Charges convicted: parole/probation violation?",
            "Charges convicted: simple assault?",
            "Have you ever spent time in a correctional institution?",
            "Did you ever spend time in a youth correctional institution?",
            "How much time did you serve, altogether? (months)",
            "Did you ever spend any time in an adult correctional institution?",
            "How much time did you serve altogether? (months)",
            "When was your most recent incarceration? (year)",
            "Were you ever required to perform community service or on probation?",
            "Why did relationship end: mother incarceration?",
            "Why did relationship end: father incarceration?",
            "What action taken: sent to jail?",
            "What is/was mother in jail for: aggravated assault?",
            "What is/was mother in jail for: major traffic offense?",
            "What is/was mother in jail for: parole/probation violation?",
            "What is/was mother in jail for: simple assault?",
            "What is/was mother in jail for: other?",
            "INT CHK: IS MOTHER CURRENTLY IN JAIL?",
            "How long did she spend in jail? (years)",
            "How long did she spend in jail? (months)",
            "How long did she spend in jail? (weeks)",
            "How long did she spend in jail? (days)",
            "When did mother go to jail? (year)",
            "When will mother be released from jail? (year)",
            "Do you currently have any charges pending against you?",
            "What charges pending: major traffic offense",
            "What charges pending: non-payment of child support",
            "What charges pending: parole or probation violation",
            "What charges pending: simple assault",
            "What charges convicted: major traffic offense",
            "What charges convicted: non-payment of child support",
            "What charges convicted: parole or probation violation",
            "What charges convicted: simple assault",
            "Ever required to perform community service or been on probation?",
            "B26X_1. Aggravated assault/rape/murder",
            "B26X_10. Domestic violence or child abuse",
            "B26X_2. Simple assault",
            "B26X_3. Robbery/theft/larceny",
            "B26X_4. Possession/use/sale of illicit drugs",
            "B26X_5. Major traffic offense",
            "B26X_6. Non-payment of child support",
            "B26X_7. Parole or probation violation",
            "B26X_9. Minor infractions",
            "D23. Current partner spent any time in jail or prison",
            "F26. You currently have charges pending against you",
            "F26B2_1. Aggravated assault/rape/murder",
            "F26B2_10. Domestic violence or child abuse",
            "F26B2_2. Simple assault",
            "F26B2_3. Robbery/theft/larceny",
            "F26B2_4. Possession/use/sale of illicit drugs",
            "F26B2_5. Major traffic offense",
            "F26B2_6. Non-payment of child support",
            "F26B2_7. Parole or probation violation",
            "F26B2_9. Minor infractions",
            "F28A_1. Aggravated assault/rape/murder",
            "F28A_10. Domestic violence or child abuse",
            "F28A_2. Simple assault",
            "F28A_3. Robbery/theft/larceny",
            "F28A_4. Possession/use/sale of illicit drugs",
            "F28A_5. Major traffic offense",
            "F28A_6. Non-payment of child support",
            "F28A_7. Parole or probation violation",
            "F28A_9. Minor infractions",
            "F28B. You have ever spent time in a correctional institution",
            "F28C. You spent time in a youth correctional institution",
            "F28E. You spent time in an adult correctional institution",
            "F29. Ever required to perform community service or been on probation",
            "Why did relationship end? Mother incarceration",
            "Why did relationship end? Father incarceration",
            "When did father go to jail/prison?-(Year)",
            "When will father be released from prison?-(Year)",
            "Has father ever spent any time in jail/prison?",
            "What was father in jail for?-Assault",
            "What was father in jail for?-Major traffic offense",
            "What was father in jail for?-Non-payment of child support",
            "What was father in jail for?-Parole or probation violation",
            "What was father in jail for?-Other",
            "What was father in jail for?-Robbery",
            "What was father in jail for?-Theft",
            "What was father in jail for?-Other property offense",
            "What was father in jail for?-Gambling",
            "How long did he spend in jail?-(Yrs)",
            "How long did he spend in jail?-(Months)",
            "How long did he spend in jail?-(Weeks)",
            "How long did he spend in jail?-(Days)",
            "Has current partner spent any time in jail or prison?",
            "Why relationship ended: mother's incarceration?",
            "Why relationship ended: father's incarceration?",
            "Has father ever spent any time in jail or prison?",
            "Why is/was father in jail: assault?",
            "Why is/was father in jail: major traffic offense?",
            "Why is/was father in jail: non-payment of child support?",
            "Why is/was father in jail: parole or probation violation?",
            "Why is/was father in jail: other?",
            "INT CHK: IS FATHER CURRENTLY IN JAIL?",
            "Approximately how long was father in jail? (years)",
            "Approximately how long was father in jail? (months)",
            "Approximately how long was father in jail? (weeks)",
            "Approximately how long was father in jail? (days)",
            "When did father go to jail/prison? (year)",
            "When will father be released from jail/prison? (year)",
            "18C ONLY: Charges pending: simple assault?",
            "When was your most recent conviction (year)?",
            "18C ONLY: Charges convicted: simple assault?",
            "Were you ever required to perform community service/been on probation?",
            "What action taken: sent father to jail?",
            "What was father in jail for: major traffic offense",
            "What was father in jail for: non-payment of child support",
            "What was father in jail for: parole or probation violation",
            "What was father in jail for: simple assault",
            "What was father in jail for: other",
            "How long did he spend in jail/prison? (years)",
            "How long did he spend in jail/prison? (months)",
            "How long did he spend in jail/prison? (weeks)",
            "How long did he spend in jail/prison? (days)",
            "What charges do you currently have pending? major traffic offense",
            "What charges do you currently have pending? non-payment of child support",
            "What charges do you currently have pending? parole or probation violation",
            "What charges were you convicted of? major traffic offense",
            "What charges were you convicted of? non-payment of child support",
            "What charges were you convicted of? parole or probation violation",
            "What charges were you convicted of? simple assault",
            "What charges were you convicted of? other",
            "B30A1_1. Aggravated assault/rape/murder",
            "B30A1_10. Domestic violence or child abuse",
            "B30A1_2. Simple assault",
            "B30A1_3. Robbery/theft/larceny",
            "B30A1_5. Major traffic offense",
            "B30A1_6. Non-payment of child support",
            "B30A1_7. Parole or probation violation",
            "B30A1_9. Minor infractions",
            "D23. Current partner has spent time in jail/prison",
            "F29. Ever required to perform community service or ever been on probation",
            "G23. Current partner ever spent time in jail?"
          ),
          class = "factor"
        ),
        old_name = structure(
          1:2,
          .Label = c(
            "cf1finjail",
            "cf2fevjail",
            "cf2finjail",
            "cf3fevjail",
            "cf3finjail",
            "cf4fevjail",
            "cf4finjail",
            "cf5fevjail",
            "cf5finjail",
            "cmf1finjail",
            "cm1finjail",
            "cm2fevjail",
            "cmf2fevjail",
            "cmf2finjail",
            "cm2finjail",
            "cm3fevjail",
            "cmf3fevjail",
            "cmf3finjail",
            "cm3finjail",
            "cm4fevjail",
            "cmf4fevjail",
            "cmf4finjail",
            "cm4finjail",
            "cm5fevjail",
            "cmf5fevjail",
            "cmf5finjail",
            "cm5finjail",
            "f2a8c",
            "f2a8d",
            "f2fh18",
            "f2fh19",
            "f2fh20",
            "f2fh20a",
            "f2h20b1",
            "f2h20b10",
            "f2h20b11",
            "f2h20b12",
            "f2h20b13",
            "f2h20b14",
            "f2h20b15",
            "f2h20b16",
            "f2h20b17",
            "f2h20b18",
            "f2h20b19",
            "f2h20b2",
            "f2h20b3",
            "f2h20b4",
            "f2h20b5",
            "f2h20b6",
            "f2h20b7",
            "f2h20b8",
            "f2h20b9",
            "f2fh21",
            "f2fh21a",
            "f2fh21b",
            "f2fh21c2",
            "f2h21d1",
            "f2h21d10",
            "f2h21d11",
            "f2h21d12",
            "f2h21d13",
            "f2h21d14",
            "f2h21d15",
            "f2h21d16",
            "f2h21d17",
            "f2h21d18",
            "f2h21d19",
            "f2h21d2",
            "f2h21d3",
            "f2h21d4",
            "f2h21d5",
            "f2h21d6",
            "f2h21d7",
            "f2h21d8",
            "f2h21d9",
            "f2fh22",
            "f2fh22a",
            "f2fh23",
            "f2fh23a",
            "f2fh24",
            "f2fh24a",
            "f2fh25",
            "f2fh25a2",
            "f2fh26b",
            "f2fh27",
            "f3a8b_3",
            "f3a8b_4",
            "f3c21d_7",
            "f3c38c_7",
            "f3c42",
            "f3c42a_4",
            "f3c42a_5",
            "f3c42a_6",
            "f3c42b",
            "f3c42c1",
            "f3c42c2",
            "f3c42c3",
            "f3c42c4",
            "f3c42d2",
            "f3c42e2",
            "f3i26",
            "f3i26b_2",
            "f3i26b_3",
            "f3i26b_4",
            "f3i26b_5",
            "f3i26b_6",
            "f3i26b_7",
            "f3i27a",
            "f3i27d2",
            "f3i28_2",
            "f3i28_3",
            "f3i28_4",
            "f3i28_5",
            "f3i28_6",
            "f3i28_7",
            "f3i29",
            "f3i30",
            "f3i30a",
            "f3i31",
            "f3i31a",
            "f3i31c2",
            "f3i32",
            "f4a8b_3",
            "f4a8b_4",
            "f4c21d_7",
            "f4c37a_1",
            "f4c37a_4",
            "f4c37a_6",
            "f4c37a_7",
            "f4c37a_8",
            "f4c37b",
            "f4c37c1",
            "f4c37c2",
            "f4c37c3",
            "f4c37c4",
            "f4c37d2",
            "f4c37e2",
            "f4i26",
            "f4i26b_4",
            "f4i26b_5",
            "f4i26b_6",
            "f4i26b_7",
            "f4i28_4",
            "f4i28_5",
            "f4i28_6",
            "f4i28_7",
            "f4i29",
            "f5b26x_1",
            "f5b26x_10",
            "f5b26x_2",
            "f5b26x_3",
            "f5b26x_4",
            "f5b26x_5",
            "f5b26x_6",
            "f5b26x_7",
            "f5b26x_9",
            "f5d23",
            "f5f26",
            "f5f26b2_1",
            "f5f26b2_10",
            "f5f26b2_2",
            "f5f26b2_3",
            "f5f26b2_4",
            "f5f26b2_5",
            "f5f26b2_6",
            "f5f26b2_7",
            "f5f26b2_9",
            "f5f28a_1",
            "f5f28a_10",
            "f5f28a_2",
            "f5f28a_3",
            "f5f28a_4",
            "f5f28a_5",
            "f5f28a_6",
            "f5f28a_7",
            "f5f28a_9",
            "f5f28b",
            "f5f28c",
            "f5f28e",
            "f5f29",
            "m2a9c",
            "m2a9d",
            "m2c33d2",
            "m2c33e2",
            "m2c36",
            "m2c36a1",
            "m2c36a14",
            "m2c36a17",
            "m2c36a18",
            "m2c36a19",
            "m2c36a2",
            "m2c36a3",
            "m2c36a7",
            "m2c36a8",
            "m2c37a1",
            "m2c37a2",
            "m2c37a3",
            "m2c37a4",
            "m2e10",
            "m3a8b_3",
            "m3a8b_4",
            "m3c42",
            "m3c42a_1",
            "m3c42a_4",
            "m3c42a_5",
            "m3c42a_6",
            "m3c42a_8",
            "m3c42b",
            "m3c42c1",
            "m3c42c2",
            "m3c42c3",
            "m3c42c4",
            "m3c42d2",
            "m3c42e2",
            "m3i26",
            "m3i26b_2",
            "m3i26b_3",
            "m3i26b_4",
            "m3i26b_5",
            "m3i26b_6",
            "m3i26b_7",
            "m3i27a",
            "m3i27d2",
            "m3i28_2",
            "m3i28_3",
            "m3i28_4",
            "m3i28_5",
            "m3i28_6",
            "m3i28_7",
            "m3i29",
            "m3i30",
            "m3i30a",
            "m3i31",
            "m3i31a",
            "m3i31c2",
            "m3i32",
            "m4a8b_3",
            "m4a8b_4",
            "m4c21d_7",
            "m4c37a_4",
            "m4c37a_5",
            "m4c37a_6",
            "m4c37a_7",
            "m4c37a_8",
            "m4c37b",
            "m4c37c1",
            "m4c37c2",
            "m4c37c3",
            "m4c37c4",
            "m4c37d2",
            "m4c37e2",
            "m4e25",
            "m4i26",
            "m4i26b_4",
            "m4i26b_5",
            "m4i26b_6",
            "m4i28_4",
            "m4i28_5",
            "m4i28_6",
            "m4i28_7",
            "m4i28_8",
            "m4i29",
            "m5b30a1_1",
            "m5b30a1_10",
            "m5b30a1_2",
            "m5b30a1_3",
            "m5b30a1_5",
            "m5b30a1_6",
            "m5b30a1_7",
            "m5b30a1_9",
            "m5d23",
            "m5f26",
            "m5f26b2_1",
            "m5f26b2_10",
            "m5f26b2_2",
            "m5f26b2_3",
            "m5f26b2_4",
            "m5f26b2_5",
            "m5f26b2_6",
            "m5f26b2_7",
            "m5f26b2_9",
            "m5f28a_1",
            "m5f28a_10",
            "m5f28a_2",
            "m5f28a_3",
            "m5f28a_4",
            "m5f28a_5",
            "m5f28a_6",
            "m5f28a_7",
            "m5f28a_9",
            "m5f28b",
            "m5f28c",
            "m5f28e",
            "m5f29",
            "p6g23"
          ),
          class = "factor"
        ),
        type = structure(
          1:2,
          .Label = c("bin", "uc", "cont"),
          class = "factor"
        ),
        warning = structure(c(1L, 1L), .Label = c("0", "2"), class = "factor"),
        group = structure(
          1:2,
          .Label = c(
            "1250",
            "1251",
            "2494",
            "5204",
            "5205",
            "5206",
            "5207",
            "5209",
            "5210",
            "5211",
            "5212",
            "5214",
            "5215",
            "5216",
            "5217",
            "5218",
            "5219",
            "5232",
            "5220",
            "5222",
            "5223",
            "5224",
            "5225",
            "5226",
            "5227",
            "5228",
            "5256",
            "5257",
            "5258",
            "5260",
            "5247",
            "5233",
            "5234",
            "5235",
            "5237",
            "5238",
            "5239",
            "5240",
            "5241",
            "5242",
            "5254",
            "5243",
            "5244",
            "5252",
            "5245",
            "5246",
            "5251",
            "5253",
            "5262",
            "5265",
            "5273",
            "5274",
            "5263",
            "5259",
            "5261",
            "5275",
            "5276",
            "62",
            "5546",
            "5547",
            "5548",
            "93",
            "5572",
            "5570",
            "5571",
            "5569",
            "5538",
            "5539",
            "237",
            "238",
            "246",
            "5264",
            "5544",
            "5558",
            "5557",
            "5554",
            "5545",
            "5550",
            "5555",
            "5556",
            "5229",
            "5230",
            "5221",
            "5213",
            "5231",
            "5248",
            "5249",
            "5236",
            "5250",
            "5543",
            "5549",
            "5551",
            "5552",
            "5553",
            "5542"
          ),
          class = "factor"
        ),
        q_group_N = structure(
          1:2,
          .Label = c("15",
                     "12", "1", "7", "6", "3", "2", "4", "5"),
          class = "factor"
        ),
        topic1 = structure(c(1L, 1L), .Label = "incarceration and policing", class = "factor"),
        topic2 = structure(
          c(1L, 1L),
          .Label = c("", "parental relationship status",
                     "child support"),
          class = "factor"
        ),
        source = structure(
          c(1L,
            1L),
          .Label = c("constructed", "questionnaire"),
          class = "factor"
        ),
        respondent = structure(c(1L, 1L), .Label = c("f", "m", "p"), class = "factor"),
        wave = structure(
          1:2,
          .Label = c("1",
                     "2", "3", "4", "5", "6"),
          class = "factor"
        ),
        scope = structure(c(1L,
                            1L), .Label = "20", class = "factor"),
        section = structure(
          c(1L,
            1L),
          .Label = c("", "a", "h", "c", "i", "b", "d", "f", "e",
                     "g"),
          class = "factor"
        ),
        leaf = structure(
          1:2,
          .Label = c(
            "finjail",
            "fevjail",
            "ffinjail",
            "ffevjail",
            "8c",
            "8d",
            "18",
            "19",
            "20",
            "20a",
            "20b1",
            "20b10",
            "20b11",
            "20b12",
            "20b13",
            "20b14",
            "20b15",
            "20b16",
            "20b17",
            "20b18",
            "20b19",
            "20b2",
            "20b3",
            "20b4",
            "20b5",
            "20b6",
            "20b7",
            "20b8",
            "20b9",
            "21",
            "21a",
            "21b",
            "21c2",
            "21d1",
            "21d10",
            "21d11",
            "21d12",
            "21d13",
            "21d14",
            "21d15",
            "21d16",
            "21d17",
            "21d18",
            "21d19",
            "21d2",
            "21d3",
            "21d4",
            "21d5",
            "21d6",
            "21d7",
            "21d8",
            "21d9",
            "22",
            "22a",
            "23",
            "23a",
            "24",
            "24a",
            "25",
            "25a2",
            "26b",
            "27",
            "8b_3",
            "8b_4",
            "21d_7",
            "38c_7",
            "42",
            "42a_4",
            "42a_5",
            "42a_6",
            "42b",
            "42c1",
            "42c2",
            "42c3",
            "42c4",
            "42d2",
            "4.20E+03",
            "26",
            "26b_2",
            "26b_3",
            "26b_4",
            "26b_5",
            "26b_6",
            "26b_7",
            "27a",
            "27d2",
            "28_2",
            "28_3",
            "28_4",
            "28_5",
            "28_6",
            "28_7",
            "29",
            "30",
            "30a",
            "31",
            "31a",
            "31c2",
            "32",
            "37a_1",
            "37a_4",
            "37a_6",
            "37a_7",
            "37a_8",
            "37b",
            "37c1",
            "37c2",
            "37c3",
            "37c4",
            "37d2",
            "3.70E+03",
            "26x_1",
            "26x_10",
            "26x_2",
            "26x_3",
            "26x_4",
            "26x_5",
            "26x_6",
            "26x_7",
            "26x_9",
            "26b2_1",
            "26b2_10",
            "26b2_2",
            "26b2_3",
            "26b2_4",
            "26b2_5",
            "26b2_6",
            "26b2_7",
            "26b2_9",
            "28a_1",
            "28a_10",
            "28a_2",
            "28a_3",
            "28a_4",
            "28a_5",
            "28a_6",
            "28a_7",
            "28a_9",
            "28b",
            "28c",
            "28e",
            "9c",
            "9d",
            "33d2",
            "3.30E+03",
            "36",
            "36a1",
            "36a14",
            "36a17",
            "36a18",
            "36a19",
            "36a2",
            "36a3",
            "36a7",
            "36a8",
            "37a1",
            "37a2",
            "37a3",
            "37a4",
            "10",
            "42a_1",
            "42a_8",
            "37a_5",
            "28_8",
            "30a1_1",
            "30a1_10",
            "30a1_2",
            "30a1_3",
            "30a1_5",
            "30a1_6",
            "30a1_7",
            "30a1_9"
          ),
          class = "factor"
        ),
        q_group_list = structure(
          1:2,
          .Label = c(
            "cm2ffinjail cm1ffinjail cm5finjail cf4finjail cm1finjail cm3ffinjail cf2finjail cm4ffinjail cm3finjail cm2finjail cf3finjail cm4finjail cm5ffinjail cf1finjail cf5finjail",
            "cm4ffevjail cf2fevjail cm5fevjail cf4fevjail cm2fevjail cm5ffevjail cm2ffevjail cm3fevjail cm4fevjail cf5fevjail cm3ffevjail cf3fevjail",
            "f4a8b_4 f4a8b_3 m2a9c f3a8b_3 m3a8b_4 m2a9d m4a8b_3 f2a8d f3a8b_4 m4a8b_4 f2a8c m3a8b_3",
            "f2h18",
            "f2h19",
            "m3i26 m4i26 f2h20 f5f26 m5f26 f4i26 f3i26",
            "f2h20a",
            "f3i26b_7 m3i26b_7 f4i26b_7 f2h20b1 f5f26b2_2 m5f26b2_2",
            "f2h20b10",
            "f2h20b11",
            "f2h20b12",
            "f2h20b13",
            "f5f26b2_5 f4i26b_4 m3i26b_4 m5f26b2_5 f3i26b_4 f2h20b14 m4i26b_4",
            "f2h20b15",
            "f2h20b16",
            "m5f26b2_6 f5f26b2_6 f2h20b17 m3i26b_5 f4i26b_5 m4i26b_5 f3i26b_5",
            "f3i26b_6 m4i26b_6 m3i26b_6 f2h20b18 f4i26b_6 f5f26b2_7 m5f26b2_7",
            "f2h20b19",
            "f2h20b2",
            "f2h20b3",
            "f2h20b4",
            "f2h20b5",
            "f2h20b6",
            "f2h20b7",
            "f2h20b8",
            "f2h20b9",
            "f2h21",
            "f3i27a m3i27a f2h21a",
            "f2h21b",
            "f3i27d2 f2h21c2 m3i27d2",
            "m4i28_7 f5f28a_2 f3i28_7 m3i28_7 f4i28_7 m5f28a_2 f2h21d1",
            "f2h21d10",
            "f2h21d11",
            "f2h21d12",
            "f2h21d13",
            "f5f28a_5 m3i28_4 m5f28a_5 m4i28_4 f3i28_4 f4i28_4 f2h21d14",
            "f2h21d15",
            "f2h21d16",
            "f2h21d17 f3i28_5 m3i28_5 f4i28_5 f5f28a_6 m5f28a_6 m4i28_5",
            "m4i28_6 m3i28_6 f2h21d18 m5f28a_7 f5f28a_7 f3i28_6 f4i28_6",
            "m4i28_8 f2h21d19",
            "f5f28a_3 f2h21d5 m5f28a_3 f2h21d2",
            "f2h21d3",
            "f2h21d4",
            "f2h21d6",
            "f2h21d7",
            "f2h21d8",
            "f2h21d9",
            "f5d23 f2h22 f3i30 m5f28b f3i29 m2e10 f3c42 m5d23 m2c36 f5f28c m3c42 m4e25",
            "f2h22a",
            "f2h23",
            "f2h24a f2h23a",
            "m3i31 m3i29 f2h24 m5f28e f5f28b",
            "f2h25",
            "f3i31c2 m3i31c2 f2h25a2",
            "f2h26b",
            "f5f29 f4i29 f3i32 f2h27 m4i29 m5f29 m3i32",
            "f4c21d_7 f3c21d_7 f3c38c_7 m4c21d_7",
            "m2c36a14 m4c37a_4 f4c37a_4 m5b30a1_5 f3c42a_4 f5b26x_5 m3c42a_4",
            "f5b26x_6 m2c36a17 m5b30a1_6 f3c42a_5 m3c42a_5 m4c37a_5",
            "f4c37a_6 m3c42a_6 f5b26x_7 m2c36a18 m4c37a_6 f3c42a_6 m5b30a1_7",
            "f4c37b f3c42b m3c42b m4c37b",
            "m3c42c1 f3c42c1 m4c37c1 m2c37a1 f4c37c1",
            "m2c37a2 f4c37c2 f3c42c2 m4c37c2 m3c42c2",
            "f3c42c3 f4c37c3 m4c37c3 m3c42c3 m2c37a3",
            "m2c37a4 m3c42c4 m4c37c4 f3c42c4 f4c37c4",
            "m3c42d2 m2c33d2 f3c42d2 f4c37d2 m4c37d2",
            "m2c33e2 m4c37e2 f3c42e2 m3c42e2 f4c37e2",
            "f3i28_2 f3i26b_2 m3i28_2 m3i26b_2",
            "f3i26b_3 f3i28_3 m3i28_3 m3i26b_3",
            "f3i30a m3i31a m3i30a f3i31a",
            "f3i31 m3i30 m5f28c f5f28e",
            "f4c37a_1 m5b30a1_1 f5b26x_1",
            "f4c37a_7",
            "m3c42a_8 f4c37a_8 m2c36a19 m4c37a_8",
            "m5b30a1_10 f5b26x_10",
            "m5b30a1_2 f5b26x_2",
            "m5b30a1_3 f5b26x_3",
            "f5b26x_4",
            "m5b30a1_9 f5b26x_9",
            "m5f26b2_1 f5f26b2_1",
            "m5f26b2_10 f5f26b2_10",
            "m5f26b2_3 f5f26b2_3",
            "f5f26b2_4 m5f26b2_4",
            "m5f26b2_9 f5f26b2_9",
            "f5f28a_1 m5f28a_1",
            "m5f28a_10 f5f28a_10",
            "m5f28a_4 f5f28a_4",
            "m5f28a_9 f5f28a_9",
            "m4c37a_7 m3c42a_1 m2c36a1",
            "m2c36a2",
            "m2c36a3",
            "m2c36a7",
            "m2c36a8",
            "p6g23"
          ),
          class = "factor"
        ),
        value1 = structure(
          c(1L,
            1L),
          .Label = c("-9", "", "-14", "-17", "-12", "-10"),
          class = "factor"
        ),
        label1 = structure(
          c(1L, 1L),
          .Label = c(
            "-9 Not in wave",
            "",
            "-14 mother died",
            "-17 In exchange",
            "-12 Still in prison",
            "-10 n/a - currently in jail"
          ),
          class = "factor"
        ),
        value2 = structure(
          c(1L,
            1L),
          .Label = c("-8", "", "-10", "-15", "-9"),
          class = "factor"
        ),
        label2 = structure(
          c(1L, 1L),
          .Label = c("-8 Out of range",
                     "", "-10 None", "-15 All my life", "-9 Not in wave"),
          class = "factor"
        ),
        value3 = structure(
          c(1L, 1L),
          .Label = c("-7", "", "-9",
                     "-12", "-8"),
          class = "factor"
        ),
        label3 = structure(
          c(1L,
            1L),
          .Label = c(
            "-7 N/A",
            "",
            "-9 Not in wave",
            "-12 Still breastfeed",
            "-8 Out of range"
          ),
          class = "factor"
        ),
        value4 = structure(
          c(1L,
            1L),
          .Label = c("-6", "", "-8", "-11", "-7"),
          class = "factor"
        ),
        label4 = structure(
          c(1L, 1L),
          .Label = c("-6 Skip", "", "-8 Out of range",
                     "-11 >12 hours", "-7 N/A"),
          class = "factor"
        ),
        value5 = structure(
          c(1L,
            1L),
          .Label = c("-5", "", "-7", "-10", "-6"),
          class = "factor"
        ),
        label5 = structure(
          c(1L, 1L),
          .Label = c("-5 Not asked",
                     "", "-7 N/A", "-10 wdnt take job", "-6 Skip"),
          class = "factor"
        ),
        value6 = structure(
          c(1L, 1L),
          .Label = c("-4", "", "-6",
                     "-9", "-5"),
          class = "factor"
        ),
        label6 = structure(
          c(1L,
            1L),
          .Label = c("-4 Multiple ans", "", "-6 Skip", "-9 Not in wave",
                     "-5 Not asked"),
          class = "factor"
        ),
        value7 = structure(
          c(1L,
            1L),
          .Label = c("-3", "", "-5", "-8", "-4"),
          class = "factor"
        ),
        label7 = structure(
          c(1L, 1L),
          .Label = c(
            "-3 Missing",
            "",
            "-5 Not asked",
            "-8 Out of range",
            "-4 Multiple ans"
          ),
          class = "factor"
        ),
        value8 = structure(
          c(1L, 1L),
          .Label = c("-2", "", "-4",
                     "-7", "-3"),
          class = "factor"
        ),
        label8 = structure(
          c(1L,
            1L),
          .Label = c("-2 Don't know", "", "-4 Multiple ans", "-7 N/A",
                     "-3 Missing"),
          class = "factor"
        ),
        value9 = structure(
          c(1L,
            1L),
          .Label = c("-1", "", "-3", "-6", "-2"),
          class = "factor"
        ),
        label9 = structure(
          c(1L, 1L),
          .Label = c("-1 Refuse", "",
                     "-3 Missing", "-6 Skip", "-2 Don't know"),
          class = "factor"
        ),
        value10 = structure(
          c(1L, 1L),
          .Label = c("0", "", "-2",
                     "-5", "1", "16", "-1"),
          class = "factor"
        ),
        label10 = structure(
          c(1L,
            1L),
          .Label = c(
            "0 No",
            "",
            "-2 Don't know",
            "-5 Not asked",
            "1 Yes",
            "16 16 and younger",
            "1 jail",
            "-1 Refuse",
            "0 no",
            "1 yes",
            "1 yes, jail",
            "1 yes, youth institution",
            "1 yes, adult institution",
            "1 Jail"
          ),
          class = "factor"
        ),
        value11 = structure(
          c(1L, 1L),
          .Label = c("1", "", "-1", "-4", "2", "1985"),
          class = "factor"
        ),
        label11 = structure(
          c(1L, 1L),
          .Label = c(
            "1 Yes",
            "",
            "-1 Refuse",
            "-4 Multiple ans",
            "2 No",
            "1985 and earlier",
            "1 yes",
            "2 no"
          ),
          class = "factor"
        ),
        value12 = structure(
          1:2,
          .Label = c("",
                     "2", "1", "-3", "101", "3"),
          class = "factor"
        ),
        label12 = structure(
          1:2,
          .Label = c(
            "",
            "2 Sometimes",
            "1 Yes",
            "-3 Missing",
            "101 Possession of weapon",
            "3 house arrest",
            "3 In jail",
            "3 House arrest",
            "101 Domestic violence",
            "101 Weapons"
          ),
          class = "factor"
        ),
        value13 = structure(
          c(1L,
            1L),
          .Label = c("", "2", "-2", "102"),
          class = "factor"
        ),
        label13 = structure(
          c(1L, 1L),
          .Label = c(
            "",
            "2 No",
            "-2 Don't know",
            "102 Minor infractions",
            "102 Traffic tickets",
            "102 Minor",
            "102 Weapons possession"
          ),
          class = "factor"
        ),
        value14 = structure(
          c(1L,
            1L),
          .Label = c("", "-1", "103"),
          class = "factor"
        ),
        label14 = structure(
          c(1L,
            1L),
          .Label = c(
            "",
            "-1 Refuse",
            "103 Arrest-related imfraction",
            "103 Arrest-related infraction",
            "103 Domestic",
            "103 Traffic tickets"
          ),
          class = "factor"
        ),
        value15 = structure(c(1L, 1L), .Label = c("",
                                                  "104"), class = "factor"),
        label15 = structure(
          c(1L, 1L),
          .Label = c("",
                     "104 Other", "104 Property offense"),
          class = "factor"
        ),
        value16 = structure(c(1L, 1L), .Label = c("", "105"), class = "factor"),
        label16 = structure(
          c(1L, 1L),
          .Label = c(
            "",
            "105 Other drug infraction",
            "105 Undetermined drug infraction",
            "105 Alcohol related"
          ),
          class = "factor"
        ),
        value17 = structure(c(1L, 1L), .Label = c("",
                                                  "106"), class = "factor"),
        label17 = structure(
          c(1L, 1L),
          .Label = c("",
                     "106 Immigration"),
          class = "factor"
        ),
        value18 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label18 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value19 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label19 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value20 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label20 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value21 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label21 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value22 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label22 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value23 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label23 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value24 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label24 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value25 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label25 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value26 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label26 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value27 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label27 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value28 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label28 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value29 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label29 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value30 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label30 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value31 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label31 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value32 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label32 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value33 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label33 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value34 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label34 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value35 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label35 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value36 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label36 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value37 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label37 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value38 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label38 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value39 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label39 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value40 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label40 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value41 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label41 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value42 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label42 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value43 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label43 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value44 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label44 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value45 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label45 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value46 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label46 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value47 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label47 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value48 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label48 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value49 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label49 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value50 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label50 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value51 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label51 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value52 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label52 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value53 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label53 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value54 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label54 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value55 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label55 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value56 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label56 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value57 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label57 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value58 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label58 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value59 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label59 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value60 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label60 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value61 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label61 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value62 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label62 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value63 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label63 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value64 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label64 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value65 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label65 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value66 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label66 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value67 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label67 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        value68 = structure(c(1L,
                              1L), .Label = "", class = "factor"),
        label68 = structure(c(1L,
                              1L), .Label = "", class = "factor")
      ),
      .Names = c(
        "new_name",
        "varlab",
        "old_name",
        "type",
        "warning",
        "group",
        "q_group_N",
        "topic1",
        "topic2",
        "source",
        "respondent",
        "wave",
        "scope",
        "section",
        "leaf",
        "q_group_list",
        "value1",
        "label1",
        "value2",
        "label2",
        "value3",
        "label3",
        "value4",
        "label4",
        "value5",
        "label5",
        "value6",
        "label6",
        "value7",
        "label7",
        "value8",
        "label8",
        "value9",
        "label9",
        "value10",
        "label10",
        "value11",
        "label11",
        "value12",
        "label12",
        "value13",
        "label13",
        "value14",
        "label14",
        "value15",
        "label15",
        "value16",
        "label16",
        "value17",
        "label17",
        "value18",
        "label18",
        "value19",
        "label19",
        "value20",
        "label20",
        "value21",
        "label21",
        "value22",
        "label22",
        "value23",
        "label23",
        "value24",
        "label24",
        "value25",
        "label25",
        "value26",
        "label26",
        "value27",
        "label27",
        "value28",
        "label28",
        "value29",
        "label29",
        "value30",
        "label30",
        "value31",
        "label31",
        "value32",
        "label32",
        "value33",
        "label33",
        "value34",
        "label34",
        "value35",
        "label35",
        "value36",
        "label36",
        "value37",
        "label37",
        "value38",
        "label38",
        "value39",
        "label39",
        "value40",
        "label40",
        "value41",
        "label41",
        "value42",
        "label42",
        "value43",
        "label43",
        "value44",
        "label44",
        "value45",
        "label45",
        "value46",
        "label46",
        "value47",
        "label47",
        "value48",
        "label48",
        "value49",
        "label49",
        "value50",
        "label50",
        "value51",
        "label51",
        "value52",
        "label52",
        "value53",
        "label53",
        "value54",
        "label54",
        "value55",
        "label55",
        "value56",
        "label56",
        "value57",
        "label57",
        "value58",
        "label58",
        "value59",
        "label59",
        "value60",
        "label60",
        "value61",
        "label61",
        "value62",
        "label62",
        "value63",
        "label63",
        "value64",
        "label64",
        "value65",
        "label65",
        "value66",
        "label66",
        "value67",
        "label67",
        "value68",
        "label68"
      ),
      row.names = 1:2,
      class = "data.frame"
    )

  search_test <-
    search_metadata(query = "policing", field_name = "topic1")
  expect_identical(search_test[1:2, ], fixture1)

})




test_that("filter test", {
  skip_on_cran()

  fixture1 <-
    structure(
      c(
        "cd3whenint",
        "ce3secondch",
        "version of interview flag",
        "second child in center",
        "ffcc_centsurvey_whenint",
        "ffcc_centobs_secondch",
        "bin",
        "bin",
        "0",
        "0",
        "883",
        "529",
        "1",
        "1",
        "* topic1 coming soon! *",
        "* topic1 coming soon! *",
        "",
        "",
        "constructed",
        "constructed",
        "d",
        "e",
        "3",
        "3",
        "20",
        "20",
        "",
        "",
        "whenint",
        "secondch",
        "cd3whenint",
        "ce3secondch",
        "-9",
        "-9",
        "-9 Not in wave",
        "-9 Not in wave",
        "-8",
        "-8",
        "-8 Out of range",
        "-8 Out of range",
        "-7",
        "-7",
        "-7 N/A",
        "-7 N/A",
        "-6",
        "-6",
        "-6 Skip",
        "-6 Skip",
        "-5",
        "-5",
        "-5 Not asked",
        "-5 Not asked",
        "-4",
        "-4",
        "-4 Multiple ans",
        "-4 Multiple ans",
        "-3",
        "-3",
        "-3 Missing",
        "-3 Missing",
        "-2",
        "-2",
        "-2 Don't know",
        "-2 Don't know",
        "-1",
        "-1",
        "-1 Refuse",
        "-1 Refuse",
        "0",
        "",
        "0 october survey",
        "",
        "1",
        "",
        "1 may survey",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
      ),
      .Dim = c(2L, 152L),
      .Dimnames = list(
        c("1",
          "2"),
        c(
          "new_name",
          "varlab",
          "old_name",
          "type",
          "warning",
          "group",
          "q_group_N",
          "topic1",
          "topic2",
          "source",
          "respondent",
          "wave",
          "scope",
          "section",
          "leaf",
          "q_group_list",
          "value1",
          "label1",
          "value2",
          "label2",
          "value3",
          "label3",
          "value4",
          "label4",
          "value5",
          "label5",
          "value6",
          "label6",
          "value7",
          "label7",
          "value8",
          "label8",
          "value9",
          "label9",
          "value10",
          "label10",
          "value11",
          "label11",
          "value12",
          "label12",
          "value13",
          "label13",
          "value14",
          "label14",
          "value15",
          "label15",
          "value16",
          "label16",
          "value17",
          "label17",
          "value18",
          "label18",
          "value19",
          "label19",
          "value20",
          "label20",
          "value21",
          "label21",
          "value22",
          "label22",
          "value23",
          "label23",
          "value24",
          "label24",
          "value25",
          "label25",
          "value26",
          "label26",
          "value27",
          "label27",
          "value28",
          "label28",
          "value29",
          "label29",
          "value30",
          "label30",
          "value31",
          "label31",
          "value32",
          "label32",
          "value33",
          "label33",
          "value34",
          "label34",
          "value35",
          "label35",
          "value36",
          "label36",
          "value37",
          "label37",
          "value38",
          "label38",
          "value39",
          "label39",
          "value40",
          "label40",
          "value41",
          "label41",
          "value42",
          "label42",
          "value43",
          "label43",
          "value44",
          "label44",
          "value45",
          "label45",
          "value46",
          "label46",
          "value47",
          "label47",
          "value48",
          "label48",
          "value49",
          "label49",
          "value50",
          "label50",
          "value51",
          "label51",
          "value52",
          "label52",
          "value53",
          "label53",
          "value54",
          "label54",
          "value55",
          "label55",
          "value56",
          "label56",
          "value57",
          "label57",
          "value58",
          "label58",
          "value59",
          "label59",
          "value60",
          "label60",
          "value61",
          "label61",
          "value62",
          "label62",
          "value63",
          "label63",
          "value64",
          "label64",
          "value65",
          "label65",
          "value66",
          "label66",
          "value67",
          "label67",
          "value68",
          "label68"
        )
      )
    )

  filter_test <-
    filter_metadata(wave = 3,
                    source = "constructed",
                    type = "bin")
  expect_identical(as.matrix(filter_test[1:2, ]), fixture1)

})
